version: '3.7'
networks:
  proxynet:
    driver: bridge

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Agenda@123"
      ACCEPT_EULA: "Y"
  
  
      